### ISSUE TITLE
Group attribute ignored when using -v & -z

### ISSUE THREAD

**Issue by kmcrawford** [newsapps/beeswithmachineguns#110]
I am specifying -v & -z  as I want to test a service in my VPC.  However when specifying a group using -g  the "a bee!" instances are being created with the default security group.

**Comment by krak3n** [comment]
@kmcrawford I had to make some alterations to the code to get this working. the patch is below. Not sure if I should PR this or not.

Note my editor sorts the imports for me.

http://pastebin.com/Ggxuhi7b
