### ISSUE TITLE
Ability to specify user agent?

### ISSUE THREAD

**Issue by bgunsberger** [newsapps/beeswithmachineguns#123]
Hi,

I apologise if this is obvious, but I couldn't see what user agent the bees use or if there was a way to specify it. I'd like to be able to filter out bees traffic from my analytics data.

Thanks.

**Comment by samdfonseca** [comment]
Set the User-Agent head with the -H/--headers flag on the attack command, ex:
```
./bees attack -H User-Agent:bees-instance ...
```

**Comment by bgunsberger** [comment]
Thanks. Sorry, that should have been obvious.
