### ISSUE TITLE
Can I use bees for multiple urls?

### ISSUE THREAD

**Issue by IBleSSeDI** [newsapps/beeswithmachineguns#133]
I would liek to simulate real users by bees. Real users don't call only one url, but different. Can I provide several urls for bees? I tried running bees attack in multiple threads, but it doesn't work, I am said that I lost connection for one of the tries. Is there any solution? Thank you.

**Comment by richardleebr** [comment]
Just submitted a pull request for this.  Hopefully it'd be accepted: https://github.com/newsapps/beeswithmachineguns/pull/149

**Comment by cosmin** [comment]
Merged

**Comment by IBleSSeDI** [comment]
@richardleebr you rock! Thank you!
