### ISSUE TITLE
('Unable to call bees:', u"Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.")

### ISSUE THREAD

**Issue by aniruddhasm** [newsapps/beeswithmachineguns#139]
Hello,

I've implemented ubuntu instance on Amazon AWS referring this links
http://wasita.net/2013/05/13/bees-with-machine-guns-on-aws-ec2/
http://blog.bluemalkin.net/load-testing-on-ec2-using-bees-with-machine-guns/

After running this command 
```
bees up -s 4 -g <my group> --key=<my key> --i=<my id> --zone=<my zone> --login=ubuntu
```
I am getting this error
('Unable to call bees:', u"Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.")

**Comment by leonardothibes** [comment]
@aniruddhasm In really, it's a problem, but you can solve this using a Paravirtual AMI type instead of HVM.

News Apps Devs, please implement a parameter to inform a machine type in a command line directly. This param will solve this problem forever.

Thanks.

**Comment by aniruddhasm** [comment]
hello I've another paravirtual AMI

Followed these below steps

http://wasita.net/2013/05/13/bees-with-machine-guns-on-aws-ec2/
http://blog.bluemalkin.net/load-testing-on-ec2-using-bees-with-machine-guns/

```
bees up -s 4 -g <my group> --key=<my key> --i=<my id> --zone=<my zone> --login=ubuntu
```

But now I am getting the below error
```
Connecting to the hive.
GroupId found: bees
Placement: us-west-2b
Attempting to call up 4 bees.
('Unable to call bees:', u'Value () for parameter groupId is invalid. The value cannot be empty')
```

Please help it's urgent

Thanks

**Comment by aniruddhasm** [comment]
Solved it by replacing  by proper group id
