### ISSUE TITLE
Request to report more specific error information

### ISSUE THREAD

**Issue by wooswiff** [newsapps/beeswithmachineguns#14]
I was stuck for a while on what ended up being a dumb mistake on my part.  I was defining my target URL like:
    http://www.mysite.com
instead of:
    http://www.mysite.com/

Unfortunately the only error message I got back was:
    Bee 0 lost sight of the target (connection timed out).

Instead of the actual ab error of:
    ab: invalid URL

It would be helpful if the actual ab error could reported (maybe in a verbose mode) instead of just the 'lost sight of target' catchall.  Or failing that, a friendly reminder in the README for forgetful folks like me to remember the trailing slash in the URL.

Thanks,
Jeff

**Comment by sanatp** [comment]
still getting this error of "Bee 0 lost sight of the target (connection timed out)." from the missing /
