### ISSUE TITLE
The bees need a security group to run under. The one specified was not found.

### ISSUE THREAD

**Issue by Hueyza** [newsapps/beeswithmachineguns#186]
Getting The bees need a security group to run under. The one specified was not found. when using a sg-id that exists in my AWS account. I've tried two different SG ids that exists and that I currently use in my VPC but still tells me it can't find the one. Anyone else run into this?

**Comment by FliesLikeABrick** [comment]
@Hueyza  the tool expects a security group name instead of ID, try using the name instead (it automatically finds the ID later).

I or someone may write a patch which helps with this by identifying if an ID was provided, and if so using that.

**Comment by FliesLikeABrick** [comment]
@cosmin  this issue can be closed due to the merge of #200
